:concurrency: 5
:queues:
  - default
:scheduler:
  :schedule:
    get_notification_targets:
      cron: '*/50 * * * *'
      class: NotificationTargetGetJob
      queue: default
      description: '50分毎に通知対象を取得'