:concurrency: 5
:queues:
  - default
:scheduler:
  :schedule:
    get_notification_targets:
      class: NotificationTargetGetJob
      queue: default
      description: '1分毎に通知対象を取得'
      every: '30s' 
